name: automerge
on: [push, pull_request]
env:
  MERGE_LABELS: ""
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.10.0"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
