name: compile upload cv
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - name: Set up Git repository
#       uses: actions/checkout@v1
#     - name: Compile CV
#       uses: xu-cheng/latex-action@master
#       with:
#         root_file: cv.tex
#         working_directory: _cv
    - name: Upload
#       uses: actions/upload-artifact@main
#       with:
#         name: cv.pdf
#         path: uploads
#       if: always()
      run: |
        echo $DEPLOY_KEY
        # configure git
        git config --global user.name "shahdloo"
        git config --global user.email "shahdloo@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        ssh -vT git@github.com
#         git clone --depth=1 git@github.com:shahdloo/shahdloo.github.io.git "$GITHUB_WORKSPACE/website"
#         cp -f cv.pdf "$GITHUB_WORKSPACE/website/uploads/cv.pdf"
#         cd "$GITHUB_WORKSPACE/website"
#         git add file/cv.pdf
#         git commit -m "[github actions] update cv"
#         git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
