name: Fetch New CV
on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event.action == 'update_cv'
        uses: actions/checkout@v1
      - name: Fetch New Resume and Push Branch
        if: github.event.action == 'update_cv'
        uses: ./commit-cv
        env:
          BRANCH: resume-bot
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_BODY: Updates cv
          PULL_REQUEST_BRANCH: main
